#define STAGE_EDGE_LEFT #$30
#define STAGE_EDGE_RIGHT #$b0
#define STAGE_EDGE_TOP #$80
#define STAGE_EDGE_BOTTOM #$ff

#define PLAYER_STATE_STANDING #$00
#define PLAYER_STATE_RUNNING #$01
#define PLAYER_STATE_FALLING #$02
#define PLAYER_STATE_JUMPING #03
#define PLAYER_STATE_JABBING #04
#define PLAYER_STATE_THROWN #05

#define DIRECTION_LEFT #$00
#define DIRECTION_RIGHT #$01

#define HITBOX_DISABLED #$00
#define HITBOX_ENABLED #$01

#define TILENUM_NT_CHAR_0 #$13
