STNP_CLI_MSG_TYPE_CONNECTION = 0
STNP_CLI_MSG_TYPE_CONTROLLER_STATE = 1

STNP_SRV_MSG_TYPE_CONNECTED = 0
STNP_SRV_MSG_TYPE_START_GAME = 1
STNP_SRV_MSG_TYPE_NEWSTATE = 2
STNP_SRV_MSG_TYPE_GAMEOVER = 3
STNP_SRV_MSG_TYPE_DISCONNECTED = 4

STNP_START_GAME_FIELD_STAGE = 1
STNP_START_GAME_FIELD_STOCK = 2
STNP_START_GAME_FIELD_PLAYER_NUMBER = 3
STNP_START_GAME_FIELD_PLAYER_CONNECTIONS = 4
STNP_START_GAME_FIELD_PA_CHARACTER = 5
STNP_START_GAME_FIELD_PB_CHARACTER = 6
STNP_START_GAME_FIELD_PA_PALETTE = 7
STNP_START_GAME_FIELD_PB_PALETTE = 8

STNP_DISCONNECTED_FIELD_REASON = 1
